[build]
  base = "."
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  SANITY_STUDIO_PROJECT_ID = "${SANITY_STUDIO_PROJECT_ID}"
  SANITY_STUDIO_DATASET = "${SANITY_STUDIO_DATASET}"
  SANITY_STUDIO_API_VERSION = "${SANITY_STUDIO_API_VERSION}"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200