[build]
  base = "."
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_PATHS = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200